#!/bin/bash
# Copyright (c) 2017, Anthony DeDominic <adedomin@gmail.com>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# Faster, user-space oriented locate and updatedb.
# System wide usage as root may expose "hidden" files.
# For system wide, amke sure to set XDG_DATA_HOME to some meaningful
# location.
#
# To ignore certain dirs, you can set a global /etc/updatedb-ignore
# which contains full paths to directories; they must not be files.
# the user can also use $XDG_CONFIG_HOME/updatedb-ignore or
# $HOME/.config/updatedb-ignore to accomplish the same thing.

if [[ "$1" == '-h' || "$1" == '--help' ]]; then
    echo "usage: $0 [-h | --help] [grep args]"$'\n' >&2
    echo '       Search the filesystem for a file.' >&2
    echo '       Run as updatedb to update.' >&2
    exit 1
fi

if [[ -n "$XDG_DATA_HOME" ]]; then
    DB_PATH="$XDG_DATA_HOME/glocate.db"
else
    DB_PATH="${HOME:?}/.local/share/glocate.db"
fi

if ! type "lz4" > /dev/null; then
    COMPRESS="gzip"
else
    COMPRESS="lz4"
fi

if [[ "$0" == *updatedb ]]; then
    mkdir -p "${DB_PATH%/*}"
    IGN_DIRS=()
    while read -r dir; do
        IGN_DIRS+=("-o" "-path" "$dir" "-prune")
    done < <(
        cat /etc/updatedb-ignore \
          "${XDG_CONFIG_HOME:-$HOME/.config}/updatedb-ignore" \
        2>/dev/null
    )
    find / -path /proc -prune \
        -o -path /sys -prune \
        -o -path /dev -prune \
        -o -path /tmp -prune \
        -o -path /run -prune \
        "${IGN_DIRS[@]}" \
        -o -print0 2> /dev/null \
    | "$COMPRESS" -1 > "$DB_PATH"
    exit 0
fi

if [[ ! -f "$DB_PATH" ]]; then
    echo "Error: Run this command as updatedb first." >&2
    exit 1
fi

"$COMPRESS" -dc "$DB_PATH" | grep -z "$@" - | tr '\0' '\n'
